### ISSUE TITLE
[bug] Some pngs silently fail to be stripped after printing `crc failure`

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/exif-terminator#5]
See image + test on branch here: https://github.com/superseriousbusiness/exif-terminator/tree/fish_png_error

Discovered by https://github.com/superseriousbusiness/gotosocial/issues/2340

**Comment by daenney** [comment]
So, on the `fish.png`, I get:

```
ExifTool Version Number         : 12.70
File Name                       : fish.png
Directory                       : images
File Size                       : 19 kB
File Modification Date/Time     : 2023:11:27 17:29:30+01:00
File Access Date/Time           : 2023:11:27 17:29:37+01:00
File Inode Change Date/Time     : 2023:11:27 17:29:30+01:00
File Permissions                : -rw-r--r--
File Type                       : PNG
File Type Extension             : png
MIME Type                       : image/png
Image Width                     : 256
Image Height                    : 256
Bit Depth                       : 8
Color Type                      : RGB
Compression                     : Deflate/Inflate
Filter                          : Adaptive
Interlace                       : Noninterlaced
SRGB Rendering                  : Perceptual
Warning                         : Error inflating eXIf
EX If                           : REF(0x563044b65658)
Apple Data Offsets              : (Binary data 28 bytes, use -b option to extract)
Image Size                      : 256x256
Megapixels                      : 0.066
```

But, on `comic.png`:

```
ExifTool Version Number         : 12.70
File Name                       : comic.png
Directory                       : images
File Size                       : 637 kB
File Modification Date/Time     : 2023:11:27 17:29:22+01:00
File Access Date/Time           : 2023:11:27 17:29:30+01:00
File Inode Change Date/Time     : 2023:11:27 17:29:22+01:00
File Permissions                : -rw-r--r--
File Type                       : PNG
File Type Extension             : png
MIME Type                       : image/png
Image Width                     : 700
Image Height                    : 715
Bit Depth                       : 8
Color Type                      : RGB with Alpha
Compression                     : Deflate/Inflate
Filter                          : Adaptive
Interlace                       : Noninterlaced
Image Size                      : 700x715
Megapixels                      : 0.500
```

An interesting difference with the `fish.png` is:

```
Warning                         : Error inflating eXIf
EX If                           : REF(0x563044b65658)
Apple Data Offsets              : (Binary data 28 bytes, use -b option to extract)
```

**Comment by daenney** [comment]
Right, it's tripping on the exif block. The CRC we got from the PNG is `1743395401`, but the value that `calculateCrc32` got for this chunk is: `2861182479`

![Screenshot from 2023-11-27 18-08-30](https://github.com/superseriousbusiness/exif-terminator/assets/569574/34db25b9-3abc-4a10-8eed-1308ef678fc0)

Which means we end up in https://github.com/dsoprea/go-png-image-structure/blob/29b889a6093d9c9999c0e61db371269b5fc037a5/png.go#L395C6-L395C6. Since we have `doCrcCheck` set, it panic logs, which `pngSplitter.Split()` recovers and wraps into an error that then gets returned https://github.com/dsoprea/go-png-image-structure/blob/29b889a6093d9c9999c0e61db371269b5fc037a5/png.go#L351-L355

**Comment by daenney** [comment]
ImageMagick can't handle that image either, for the same reason:

```
convert fish.png fish.jpeg
convert: eXIf: CRC error `fish.png' @ warning/png.c/MagickPNGWarningHandler/1526.
convert: eXIf: incorrect byte-order specifier `fish.png' @ warning/png.c/MagickPNGWarningHandler/1526.
```

**Comment by daenney** [comment]
Exif is an ancillary chunk, so we can ignore the CRC entirely in that case as it doesn't really matter. However, we don't seem to be able to do that with that library.

I wonder if it wouldn't be better to use the approach in https://github.com/google/wuffs/blob/414a011491ff513b86d8694c5d71800f3cb5a715/script/strip-png-ancillary-chunks.go, and strip ancillary chunks instead we don't care for, like exif, directly instead.

**Comment by daenney** [comment]
An alternative would be to change the go-png-image-structure library to allow skipping the CRC but only for ancillary chunks. That should let us process things properly, and for critical chunks we'd still check the checksum.

I have no idea why this image has a CRC error on the exif chunk though. Or how it ended up with an incorrect byte order specifier (assuming that that's actually the error and not some heuristic in imagemagick that got tripped up).

**Comment by tsmethurst** [comment]
*some* of the exif stuff gets kept, that's one thing we need to keep in mind: we keep the rotation data from the exif so that we don't have to rotate + reencode the image (which is relatively v. expensive)

also worth noting that fish.png has passed through exif terminator, since it's a profile picture from a GoToSocial instance, so it's probably stripping the exif off that broke the CRC

if there's a way we can just remove the CRC that would be nice; does it seem like a lot of work?

**Comment by daenney** [comment]
The CRC is required for each chunk, it's even present for chunks without data (as far as I remember the PNG spec). So unfortunately, I don't think we can't just drop the CRC. Best we could do is ignore it on ancillary chunks if those fail the CRC check, since they don't contain critical info.

**Comment by daenney** [comment]
> also worth noting that fish.png has passed through exif terminator, since it's a profile picture from a GoToSocial instance, so it's probably stripping the exif off that broke the CRC

Wait, how's that possible? That would suggest getting it through exif-terminator broke it? Can we get the original from the author and see what might've happened?

**Comment by daenney** [comment]
> some of the exif stuff gets kept, that's one thing we need to keep in mind: we keep the rotation data from the exif so that we don't have to rotate + reencode the image (which is relatively v. expensive)

So, this seems to be true for JPEG, but unless I'm missing something from the PNG codepath we don't do it there: https://github.com/superseriousbusiness/exif-terminator/blob/39140829568046e6600735c7549556d4dc787651/png.go#L77-L82

I think the issue is right there, a bit later in the code: https://github.com/superseriousbusiness/exif-terminator/blob/39140829568046e6600735c7549556d4dc787651/png.go#L88-L90. We write the old chunk CRC back, but that's not going to be valid if you've just blanked out the exif chunk.
